General:
  Limt: 60
  Colored-Descriptions: true
  Player-Click:
    Enabled: true
    Cooldown-Ticks: 20
    Messages:
      - '&fUsername: &a%username%'
      - '&fCharacter Description: &b%description%'
    Sound:
      Enabled: true
      Type: ENTITY_ITEM_PICKUP
    Disabled-Worlds:
      - disabled_world_name
  Messages:
    No-Console: '&cYou cannot use this command via console.'
    No-Permission: '&cYou do not have permission to perform this command.'
    Enter-Player: '&cPlease enter a players username!'
    No-Player: '&cSorry, but we cannot find this player in your server!'
Commands:
  ViewDesc:
    Messages:
      Description: '&fYour Description: &b%description%'
  SetDesc:
    Messages:
      Description-Set: '&aYour description has successfully been set!'
      Description-Reset: '&aYour description has been reset successfully!'
      Enter-Description: '&cPlease enter a description to set!'
      Too-Long: '&cSorry, but descriptions cannot exceed %limit% characters!'
  ForceDesc:
    Messages:
      Description-Set: '&aYou have successfully set %target%''s description!'
      Description-Reset: '&aYou have successfully reset %target%''s description!'
      No-Description: '&c%target% does not have a description to reset!'
